name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install box2d v3 from source, without examples
        run: |
          git clone https://github.com/erincatto/box2d.git
          cd box2d
          git checkout v3.1.1
          mkdir build && cd build
          cmake -DBOX2D_SAMPLES=OFF -DBOX2D_DOCS=OFF -DBOX2D_VALIDATE=OFF -DBOX2D_UNIT_TESTS=OFF ..
          cmake --build .
          sudo make install

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install required libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libvulkan-dev vulkan-tools glslc libsdl2-dev liblz4-dev liblua5.4-dev libpng-dev libsquish-dev libopenal-dev libopusfile-dev

      - name: Build and install ImGui with Vulkan backend
        run: |
          git clone https://github.com/ocornut/imgui.git
          cd imgui
          git checkout v1.92.4
          mkdir build
          cd build
          cmake .. -DIMGUI_BUILD_VULKAN_BINDING=ON -DCMAKE_INSTALL_PREFIX=/usr
          make
          sudo make install
          cd ../..
          rm -rf imgui

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          quiet: true
          cache: true

      - name: Build the project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Cleanup Box2D/imgui folders
        run: |
          git rm --cached -r box2d || true
          rm -rf box2d 2>/dev/null || true
          git rm --cached -r imgui || true
          rm -rf imgui 2>/dev/null || true